// Swift standard library type completions.
// These are used when no indexed symbols are available for Swift files.
#[allow(dead_code)]
pub(crate) static SWIFT_STDLIB_SYMBOLS: &[(&str, &str)] = &[
    // Foundation
    ("String", "struct String"),
    ("Int", "struct Int"),
    ("Double", "struct Double"),
    ("Float", "struct Float"),
    ("Bool", "struct Bool"),
    ("Array", "struct Array<Element>"),
    ("Dictionary", "struct Dictionary<Key, Value>"),
    ("Set", "struct Set<Element>"),
    ("Optional", "enum Optional<Wrapped>"),
    ("Data", "struct Data"),
    ("Date", "struct Date"),
    ("URL", "struct URL"),
    ("Error", "protocol Error"),
    ("Codable", "typealias Codable = Decodable & Encodable"),
    ("Decodable", "protocol Decodable"),
    ("Encodable", "protocol Encodable"),
    ("Equatable", "protocol Equatable"),
    ("Hashable", "protocol Hashable"),
    ("Comparable", "protocol Comparable"),
    ("Identifiable", "protocol Identifiable"),
    ("Sendable", "protocol Sendable"),
    // SwiftUI
    ("View", "protocol View"),
    ("Text", "struct Text"),
    ("Image", "struct Image"),
    ("Button", "struct Button"),
    ("HStack", "struct HStack"),
    ("VStack", "struct VStack"),
    ("ZStack", "struct ZStack"),
    ("List", "struct List"),
    ("NavigationStack", "struct NavigationStack"),
    ("NavigationLink", "struct NavigationLink"),
    ("Spacer", "struct Spacer"),
    ("Divider", "struct Divider"),
    ("Color", "struct Color"),
    ("Shape", "protocol Shape"),
    ("Padding", "struct Padding"),
    ("Frame", "struct Frame"),
    ("State", "@propertyWrapper struct State"),
    ("Binding", "@propertyWrapper struct Binding"),
    ("ObservedObject", "@propertyWrapper struct ObservedObject"),
    ("StateObject", "@propertyWrapper struct StateObject"),
    (
        "EnvironmentObject",
        "@propertyWrapper struct EnvironmentObject",
    ),
    ("Published", "@propertyWrapper struct Published"),
    ("ObservableObject", "protocol ObservableObject"),
    ("Environment", "@propertyWrapper struct Environment"),
    ("App", "protocol App"),
    ("Scene", "protocol Scene"),
    ("WindowGroup", "struct WindowGroup"),
    // UIKit
    ("UIView", "class UIView"),
    ("UIViewController", "class UIViewController"),
    ("UITableView", "class UITableView"),
    ("UICollectionView", "class UICollectionView"),
    ("UILabel", "class UILabel"),
    ("UIButton", "class UIButton"),
    ("UIImageView", "class UIImageView"),
    ("UIStackView", "class UIStackView"),
    ("UINavigationController", "class UINavigationController"),
    ("UITabBarController", "class UITabBarController"),
    ("UIAlertController", "class UIAlertController"),
    ("UITableViewCell", "class UITableViewCell"),
    ("UICollectionViewCell", "class UICollectionViewCell"),
    ("UIColor", "class UIColor"),
    ("UIImage", "class UIImage"),
    ("UIFont", "class UIFont"),
    ("CGRect", "struct CGRect"),
    ("CGSize", "struct CGSize"),
    ("CGPoint", "struct CGPoint"),
    ("CGFloat", "struct CGFloat"),
    // Combine
    ("Publisher", "protocol Publisher"),
    ("Subscriber", "protocol Subscriber"),
    ("Subject", "protocol Subject"),
    ("PassthroughSubject", "class PassthroughSubject"),
    ("CurrentValueSubject", "class CurrentValueSubject"),
    ("AnyPublisher", "struct AnyPublisher"),
    ("AnyCancellable", "class AnyCancellable"),
    ("Cancellable", "protocol Cancellable"),
    ("Just", "struct Just"),
    ("Future", "struct Future"),
];
